### ISSUE TITLE
How to print all action properties?

### ISSUE THREAD

**Issue by leonprou** [brianegan/redux_logging#15]
I've come from the JS world and printing the object props was the default behaviour there.
Here everything is classes and printing a class gives me just the instance: `Instance of MyAction`.

Maybe there's some known recipe to make a `redux_logging` behave like a JS version?

**Comment by brianegan** [comment]
Hey there -- unfortunately, there is no built in mechanism to print all of the props of an object without using Reflection. Since reflection isn't supported by Flutter, I haven't implemented it in this library.

In general, Dart requires end-users to implement the `toString` method on their classes to print the correct results.

Languages like Scala and Kotlin have support for "Data Classes" that automatically generate an appropriate `toString` method for ya. Hopefully that feature will come to Dart in the next year or so!

**Comment by leonprou** [comment]
I see, thanks for the answer 👍 .
Hope for more improvements in Dart :)
