### ISSUE TITLE
Upgrade logging package to 1.2.0

### ISSUE THREAD

**Issue by teddy-dubal** [brianegan/redux_logging#22]
Hi !

Thanks for this package, its very useful.
Could you just update the logging package to 1.2.0?
This causes conflicts in some projects.

Thank you very much

**Comment by ElDuderini** [comment]
There is currently a pull request open that fixes this issue that's been open since last year, just comes down to it getting merged in now. https://github.com/brianegan/redux_logging/pull/20

In the meantime though, you can use a fork of that branch within your pubspec file like this if you need it for resolving dependency issues with your other plugins.

redux_logging:
    git:
      url: https://github.com/bwu-dart/redux_logging

**Comment by brianegan** [comment]
Fixed and published as version 0.5.1. Thanks for the heads up.

**Comment by ElDuderini** [comment]
Great, thank you!
